
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package ada95compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 25;
  public static final int FUNCTION = 38;
  public static final int POT = 9;
  public static final int PUT = 17;
  public static final int GEQUAL = 45;
  public static final int ELSIF = 20;
  public static final int INTEGER = 2;
  public static final int GREATER = 47;
  public static final int OUT = 53;
  public static final int LESS = 48;
  public static final int FOR = 22;
  public static final int INOUT = 51;
  public static final int NOT = 15;
  public static final int SEMICOLON = 28;
  public static final int IS = 34;
  public static final int AND = 13;
  public static final int RPAR = 31;
  public static final int UMIN = 12;
  public static final int IN = 52;
  public static final int OR = 14;
  public static final int COMMA = 27;
  public static final int GET = 16;
  public static final int BEGIN = 35;
  public static final int DIV = 11;
  public static final int LOOP = 23;
  public static final int EXIT = 24;
  public static final int MAIN = 54;
  public static final int ASSIGN = 50;
  public static final int MIN = 8;
  public static final int IF = 18;
  public static final int STRINGCONT = 43;
  public static final int ID = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 39;
  public static final int EQUAL = 49;
  public static final int TRUE = 5;
  public static final int DISTINCT = 46;
  public static final int error = 1;
  public static final int MUL = 10;
  public static final int ADD = 7;
  public static final int DECLARE = 37;
  public static final int COLON = 29;
  public static final int ELSE = 21;
  public static final int LEQUAL = 44;
  public static final int WHILE = 26;
  public static final int FLOAT = 4;
  public static final int THEN = 19;
  public static final int END = 36;
  public static final int LPAR = 30;
  public static final int RANK = 32;
  public static final int FALSE = 6;
  public static final int INTEGERN = 42;
  public static final int PROCEDURE = 33;
  public static final int FLOATN = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "BOOLEAN",
  "FLOAT",
  "TRUE",
  "FALSE",
  "ADD",
  "MIN",
  "POT",
  "MUL",
  "DIV",
  "UMIN",
  "AND",
  "OR",
  "NOT",
  "GET",
  "PUT",
  "IF",
  "THEN",
  "ELSIF",
  "ELSE",
  "FOR",
  "LOOP",
  "EXIT",
  "WHEN",
  "WHILE",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "LPAR",
  "RPAR",
  "RANK",
  "PROCEDURE",
  "IS",
  "BEGIN",
  "END",
  "DECLARE",
  "FUNCTION",
  "RETURN",
  "ID",
  "FLOATN",
  "INTEGERN",
  "STRINGCONT",
  "LEQUAL",
  "GEQUAL",
  "DISTINCT",
  "GREATER",
  "LESS",
  "EQUAL",
  "ASSIGN",
  "INOUT",
  "IN",
  "OUT",
  "MAIN"
  };
}

