
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 25 15:55:08 CST 2016
//----------------------------------------------------

package ada95compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 24;
  public static final int FUNCTION = 36;
  public static final int POT = 9;
  public static final int PUT = 16;
  public static final int GEQUAL = 43;
  public static final int ELSIF = 19;
  public static final int INTEGER = 2;
  public static final int GREATER = 45;
  public static final int OUT = 51;
  public static final int LESS = 46;
  public static final int FOR = 21;
  public static final int INOUT = 49;
  public static final int NOT = 14;
  public static final int SEMICOLON = 27;
  public static final int IS = 32;
  public static final int AND = 12;
  public static final int RPAR = 30;
  public static final int IN = 50;
  public static final int OR = 13;
  public static final int COMMA = 26;
  public static final int GET = 15;
  public static final int DIV = 11;
  public static final int BEGIN = 33;
  public static final int LOOP = 22;
  public static final int EXIT = 23;
  public static final int MAIN = 52;
  public static final int ASSIGN = 48;
  public static final int MIN = 8;
  public static final int IF = 17;
  public static final int STRINGCONT = 41;
  public static final int ID = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 37;
  public static final int EQUAL = 47;
  public static final int TRUE = 5;
  public static final int DISTINCT = 44;
  public static final int error = 1;
  public static final int MUL = 10;
  public static final int ADD = 7;
  public static final int DECLARE = 35;
  public static final int COLON = 28;
  public static final int ELSE = 20;
  public static final int LEQUAL = 42;
  public static final int WHILE = 25;
  public static final int FLOAT = 4;
  public static final int THEN = 18;
  public static final int END = 34;
  public static final int LPAR = 29;
  public static final int FALSE = 6;
  public static final int INTEGERN = 40;
  public static final int PROCEDURE = 31;
  public static final int FLOATN = 39;
}

